"""empty message

Revision ID: 0db9f2616048
Revises: 599d134770cf
Create Date: 2021-11-04 16:36:27.918901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db9f2616048'
down_revision = '599d134770cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('address', sa.String(), nullable=True))
    op.add_column('Orders', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Orders', 'phone_number')
    op.drop_column('Orders', 'address')
    # ### end Alembic commands ###
