"""empty message

Revision ID: 3f811a23e23b
Revises: f71224adc921
Create Date: 2021-11-04 15:55:42.610873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f811a23e23b'
down_revision = 'f71224adc921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OrdersPositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['MenuPosition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Orders_positions')
    op.add_column('Orders', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Orders', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Orders', type_='foreignkey')
    op.drop_column('Orders', 'user_id')
    op.create_table('Orders_positions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Orders_positions_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Orders_positions_pkey')
    )
    op.drop_table('OrdersPositions')
    # ### end Alembic commands ###
