"""empty message

Revision ID: 4925acd96c76
Revises: 579a983259b2
Create Date: 2021-10-27 23:21:09.362739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4925acd96c76'
down_revision = '579a983259b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MenuPosition', 'picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MenuPosition', sa.Column('picture', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
