"""empty message

Revision ID: 4dbc044a5f1a
Revises: 961a08b3af97
Create Date: 2021-10-27 23:44:35.575987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dbc044a5f1a'
down_revision = '961a08b3af97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MenuPosition', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.drop_column('MenuPosition', 'picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MenuPosition', sa.Column('picture', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('MenuPosition', 'image')
    # ### end Alembic commands ###
