"""empty message

Revision ID: 85d97e641a2a
Revises: 9ced4a7198a6
Create Date: 2021-11-04 15:42:45.707916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d97e641a2a'
down_revision = '9ced4a7198a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Orders_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('Orders', 'positions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('positions', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('Orders_positions')
    # ### end Alembic commands ###
