"""empty message

Revision ID: 961a08b3af97
Revises: 4925acd96c76
Create Date: 2021-10-27 23:21:34.693976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961a08b3af97'
down_revision = '4925acd96c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MenuPosition', sa.Column('picture', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MenuPosition', 'picture')
    # ### end Alembic commands ###
