"""empty message

Revision ID: f71224adc921
Revises: 85d97e641a2a
Create Date: 2021-11-04 15:43:32.799749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71224adc921'
down_revision = '85d97e641a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Orders_positions', 'position_id')
    op.drop_column('Orders_positions', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders_positions', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Orders_positions', sa.Column('position_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
